// GENERATED by code/13_site_figures.py -- do not edit by hand.
// Re-run that script after any model change; it recomputes these from the saved model and the
// output/*.csv the notebooks wrote, so the charts on the page cannot drift from the paper.

/** Effect of accessibility on attendance, restated in the reader's units: the percent change in
 *  attendance for each doubling of the population within 60 minutes. Derived from the log-log
 *  coefficient as 2**b - 1. */
export const accessibilityEffect = {
  pointPct: 13.07,
  lowPct: 0.65,
  highPct: 27.01,
  pValue: 0.0385,
  games: 950,
}

/** Leave-one-venue-out error, one row per team-venue pair, ascending by miss. */
export type VenueError = { team: string; venue: string; mae: number; meanAttendance: number; games: number }
export const venueErrors: VenueError[] = [
  { team: "Racing Louisville FC", venue: "Lynn Family Stadium", mae: 1159, meanAttendance: 5844, games: 62 },
  { team: "Washington Spirit", venue: "Maryland SoccerPlex", mae: 1173, meanAttendance: 3615, games: 44 },
  { team: "Seattle Reign FC", venue: "Cheney Stadium", mae: 1348, meanAttendance: 5213, games: 12 },
  { team: "North Carolina Courage", venue: "WakeMed Soccer Park", mae: 1819, meanAttendance: 5868, games: 103 },
  { team: "Orlando Pride", venue: "Inter&Co Stadium", mae: 2561, meanAttendance: 6798, games: 98 },
  { team: "Utah Royals FC", venue: "America First Field", mae: 2678, meanAttendance: 9777, games: 59 },
  { team: "Houston Dash", venue: "Shell Energy Stadium", mae: 2748, meanAttendance: 5433, games: 107 },
  { team: "Seattle Reign FC", venue: "Lumen Field", mae: 2856, meanAttendance: 9074, games: 61 },
  { team: "NJ/NY Gotham FC", venue: "Sports Illustrated Stadium", mae: 3016, meanAttendance: 7393, games: 63 },
  { team: "San Diego Wave FC", venue: "Torero Stadium", mae: 3615, meanAttendance: 5289, games: 11 },
  { team: "Bay FC", venue: "PayPal Park", mae: 4278, meanAttendance: 12795, games: 33 },
  { team: "Chicago Stars FC", venue: "Northwestern Stadium", mae: 4722, meanAttendance: 4368, games: 9 },
  { team: "Washington Spirit", venue: "Audi Field", mae: 4826, meanAttendance: 12963, games: 58 },
  { team: "Kansas City Current", venue: "Children's Mercy Park", mae: 6210, meanAttendance: 8759, games: 30 },
  { team: "Angel City FC", venue: "BMO Stadium", mae: 7785, meanAttendance: 16435, games: 41 },
  { team: "San Diego Wave FC", venue: "Snapdragon Stadium", mae: 9392, meanAttendance: 16495, games: 48 },
  { team: "Portland Thorns FC", venue: "Providence Park", mae: 10448, meanAttendance: 17945, games: 111 },
]

/** Contribution of each input to the predicted Harrison-to-Queens change, as a percent effect on
 *  attendance. These combine multiplicatively, not additively. */
export type MechanismBar = { label: string; pct: number }
export const mechanismShift: MechanismBar[] = [
  { label: "Years at the venue", pct: -3.09 },
  { label: "Points from a playoff place", pct: -2.48 },
  { label: "Season", pct: -2.05 },
  { label: "Years in the league", pct: -1.27 },
  { label: "Day of the week", pct: -1.11 },
  { label: "Share of the city commuting by transit", pct: -0.72 },
  { label: "Recent form", pct: -0.57 },
  { label: "Gotham's league position", pct: -0.34 },
  { label: "Transit stops nearby", pct: -0.26 },
  { label: "Stadium capacity", pct: -0.16 },
  { label: "Opponent's league position", pct: -0.14 },
  { label: "Which opponent", pct: -0.05 },
  { label: "Days since the last home game", pct: -0.04 },
  { label: "Soccer-specific ground", pct: 0.02 },
  { label: "Past sellout rate", pct: 0.02 },
  { label: "Rain", pct: 0.56 },
  { label: "Shares the ground with an MLS club", pct: 0.70 },
  { label: "Temperature", pct: 0.71 },
  { label: "Which home team", pct: 3.61 },
  { label: "Which venue", pct: 12.28 },
  { label: "People who can reach the stadium", pct: 21.81 },
]
export const mechanismNetPct = 27.7

export const CHART_SOURCE =
  'American Soccer Analysis; U.S. Census Bureau (ACS 5-year); transit agency GTFS feeds; OpenStreetMap'
